/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// ComponentStatusListerExpansion allows custom methods to be added to
// ComponentStatusLister.
type ComponentStatusListerExpansion any

// ConfigMapListerExpansion allows custom methods to be added to
// ConfigMapLister.
type ConfigMapListerExpansion any

// ConfigMapNamespaceListerExpansion allows custom methods to be added to
// ConfigMapNamespaceLister.
type ConfigMapNamespaceListerExpansion any

// EndpointsListerExpansion allows custom methods to be added to
// EndpointsLister.
type EndpointsListerExpansion any

// EndpointsNamespaceListerExpansion allows custom methods to be added to
// EndpointsNamespaceLister.
type EndpointsNamespaceListerExpansion any

// EventListerExpansion allows custom methods to be added to
// EventLister.
type EventListerExpansion any

// EventNamespaceListerExpansion allows custom methods to be added to
// EventNamespaceLister.
type EventNamespaceListerExpansion any

// LimitRangeListerExpansion allows custom methods to be added to
// LimitRangeLister.
type LimitRangeListerExpansion any

// LimitRangeNamespaceListerExpansion allows custom methods to be added to
// LimitRangeNamespaceLister.
type LimitRangeNamespaceListerExpansion any

// NamespaceListerExpansion allows custom methods to be added to
// NamespaceLister.
type NamespaceListerExpansion any

// NodeListerExpansion allows custom methods to be added to
// NodeLister.
type NodeListerExpansion any

// PersistentVolumeListerExpansion allows custom methods to be added to
// PersistentVolumeLister.
type PersistentVolumeListerExpansion any

// PersistentVolumeClaimListerExpansion allows custom methods to be added to
// PersistentVolumeClaimLister.
type PersistentVolumeClaimListerExpansion any

// PersistentVolumeClaimNamespaceListerExpansion allows custom methods to be added to
// PersistentVolumeClaimNamespaceLister.
type PersistentVolumeClaimNamespaceListerExpansion any

// PodListerExpansion allows custom methods to be added to
// PodLister.
type PodListerExpansion any

// PodNamespaceListerExpansion allows custom methods to be added to
// PodNamespaceLister.
type PodNamespaceListerExpansion any

// PodTemplateListerExpansion allows custom methods to be added to
// PodTemplateLister.
type PodTemplateListerExpansion any

// PodTemplateNamespaceListerExpansion allows custom methods to be added to
// PodTemplateNamespaceLister.
type PodTemplateNamespaceListerExpansion any

// ResourceQuotaListerExpansion allows custom methods to be added to
// ResourceQuotaLister.
type ResourceQuotaListerExpansion any

// ResourceQuotaNamespaceListerExpansion allows custom methods to be added to
// ResourceQuotaNamespaceLister.
type ResourceQuotaNamespaceListerExpansion any

// SecretListerExpansion allows custom methods to be added to
// SecretLister.
type SecretListerExpansion any

// SecretNamespaceListerExpansion allows custom methods to be added to
// SecretNamespaceLister.
type SecretNamespaceListerExpansion any

// ServiceListerExpansion allows custom methods to be added to
// ServiceLister.
type ServiceListerExpansion any

// ServiceNamespaceListerExpansion allows custom methods to be added to
// ServiceNamespaceLister.
type ServiceNamespaceListerExpansion any

// ServiceAccountListerExpansion allows custom methods to be added to
// ServiceAccountLister.
type ServiceAccountListerExpansion any

// ServiceAccountNamespaceListerExpansion allows custom methods to be added to
// ServiceAccountNamespaceLister.
type ServiceAccountNamespaceListerExpansion any
